version: 2

models:
  - name: mart_customer_360
    description: "OBT com a visão 360 do Cliente (AOV, LTV, Churn, RFM)."
    columns:
      - name: sk_customer
        data_tests:
          - unique
          - not_null
      - name: total_orders
        description: "Frequência total de compras."
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
      - name: churn_risk_score
        description: "Score preditivo baseado em heurística de Recency."
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: [0.05, 0.15, 0.30, 0.60, 0.80, 0.95]
      - name: customer_health_score
        description: "Score composto baseado no segmento RFM."
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0.0
                max_value: 1.0
      - name: is_churned
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_type_list:
              arguments:
                column_type_list: ['boolean', 'bool']

  - name: mart_product_360
    description: "OBT com a visão 360 do Produto (Velocity, Turnover, Lifecycle)."
    columns:
      - name: sk_product
        data_tests:
          - unique
          - not_null
      - name: days_of_inventory
        description: "Cobertura de estoque baseada na velocidade dos últimos 30 dias."
        data_tests:
          - not_null
      - name: product_lifecycle_stage
        description: "Classificação do momento de vida do produto com base no crescimento de receita."
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: ['NO_RECENT_SALES', 'INTRODUCTION', 'GROWTH', 'DECLINE', 'MATURITY']
      - name: is_stockout_risk
        description: "Flag para alertar ruptura de estoque iminente."
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_type_list:
              arguments:
                column_type_list: ['boolean', 'bool']