version: 2

models:
  
  - name: dim_customers
    description: "Dimensão de Clientes com Surrogate Keys e atributos descritivos."
    columns:
      - name: sk_customer
        description: "Surrogate Key (Hash MD5 do ctm_customer_id)."
        data_tests:
          - unique
          - not_null
      - name: nk_customer_id
        description: "Natural Key vinda do ERP."
        data_tests:
          - not_null

  - name: dim_products
    description: "Dimensão desnormalizada de Produtos (inclui Fornecedor e Categoria)."
    columns:
      - name: sk_product
        data_tests:
          - unique
          - not_null
      - name: nk_product_id
        data_tests:
          - not_null
      - name: prd_unit_price
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 10000

  - name: dim_employees
    description: "Dimensão de Funcionários com hierarquia embutida."
    columns:
      - name: sk_employee
        data_tests:
          - unique
          - not_null
      - name: sk_manager
        description: "Surrogate Key apontando para o gestor."
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_employees')
                field: sk_employee

  - name: dim_shippers
    description: "Dimensão de Transportadoras."
    columns:
      - name: sk_shipper
        data_tests:
          - unique
          - not_null

  - name: dim_customer_demographics
    description: "Dimensão Demográfica / Segmentação RFM de Clientes."
    columns:
      - name: sk_customer_demographic
        data_tests:
          - unique
          - not_null

  - name: dim_region
    description: "Dimensão de Regiões Macro."
    columns:
      - name: sk_region
        data_tests:
          - unique
          - not_null

  - name: dim_territories
    description: "Dimensão de Territórios."
    columns:
      - name: sk_territory
        data_tests:
          - unique
          - not_null
      - name: sk_region
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_region')
                field: sk_region

  - name: dim_us_states
    description: "Dimensão de Estados Americanos."
    columns:
      - name: sk_us_state
        data_tests:
          - unique
          - not_null

  - name: fct_orders
    description: "Fato de pedidos contendo as SKs das dimensões."
    data_tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: >-
              ord_order_date <= ord_required_date
    columns:
      - name: sk_order
        data_tests:
          - unique
          - not_null
      - name: sk_customer
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: sk_customer
      - name: sk_employee
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_employees')
                field: sk_employee
      - name: sk_shipper
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_shippers')
                field: sk_shipper

  - name: fct_order_details
    description: "Fato de detalhes do pedido (Grão: Linha do Pedido)."
    columns:
      - name: sk_order_detail
        data_tests:
          - unique
          - not_null
      - name: sk_order
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('fct_orders')
                field: sk_order
      - name: sk_product
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: sk_product
      - name: ord_discount
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 1

  - name: fct_customer_demo
    description: "Tabela Bridge ligando Clientes aos seus Segmentos Demográficos (RFM)."
    columns:
      - name: sk_customer_demo
        data_tests:
          - unique
          - not_null
      - name: sk_customer
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: sk_customer
      - name: sk_customer_demographic
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customer_demographics')
                field: sk_customer_demographic

  - name: fct_employee_territories
    description: "Tabela Bridge ligando Funcionários aos seus Territórios."
    columns:
      - name: sk_employee_territory
        data_tests:
          - unique
          - not_null
      - name: sk_employee
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_employees')
                field: sk_employee
      - name: sk_territory
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_territories')
                field: sk_territory